# Ames Housing

Remember our earlier work with the Ames Housing dataset.  Here, our goal is to create a model that predicts that `SalePrice` column of the dataset.  For us, this is a regression problem.  You are to explore the data using each appropriate model that we have learned in order to compare the performance.  In one hour, I will provide you with a test set to determine the performance of your individual model.  

Consider the following:

- Features and Data Types
- Missing Values
- Distributions of Variables
- Visualizations
- Correlations
- Transformations on Data?

---

- Fix and remove outliers
- Fill in missing values
- Feature Selection
- Encoding
- Transform features
- Scale with Standardization or Normalization

---

- Identify possible models
- Compare performance with cross-validation by examining mean and standard deviation across folds
- Analyze significant variables for each model
- Examine errors being made

---

- Fine-tune parameters with cross-validation
- Try ensemble methods
- Finalize and examine on test data
- Present!

In [4]:
import pandas as pd

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [5]:
ames = pd.read_csv('data/ames_housing.csv', index_col='Id')

In [6]:
ames.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [7]:
from sklearn.pipeline import make_pipeline

In [8]:
from sklearn.grid_search import GridSearchCV

In [10]:
ames.select_dtypes('object').columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [12]:
dum_df = pd.get_dummies(ames)